# Generated by Django 4.1.6 on 2023-02-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_books', '0002_books_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='slug',
        ),
        migrations.AddField(
            model_name='books',
            name='time_delta',
            field=models.IntegerField(null=True),
        ),
    ]
